language: python

# Caching GSL and CLASS
cache:
  directories:
    - $HOME/build/EiffL/CCL/build/GSL
    - $HOME/build/EiffL/CCL/build/CLASS

python:
  - "2.7"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - fftw3
      - fftw3-dev
      - pkg-config
      - libgsl0-dev
      - swig
      - cmake

install: true

script:
    - cmake --version
    - python setup.py build
    - python setup.py test
    - sudo make -Cbuild install
    - check_ccl
