language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    packages:
      - fftw3
      - fftw3-dev
      - pkg-config
      - libgsl0-dev
      - swig
      - python-numpy
      - python3-numpy

install:
   - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
   - sudo sh cmake-3.9.1-Linux-x86_64.sh

script:
    - python setup.py build
    - python setup.py test
    - sudo make -Cbuild install
    - check_ccl
