language: c

# Compiler selection
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - fftw3
      - fftw3-dev
      - pkg-config
      - cmake
      - libgsl0-dev
      - swig
      - python3-numpy


# Installs system level dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake fftw gsl swig numpy; fi

install: true

script:
    - mkdir build
    - cmake -H. -Bbuild
    - sudo make -Cbuild install
    - check_ccl
    - python setup.py build
    - python setup.py test
