language: python

# Caching all the depencencies so that they don't have to be redownloaded and
# compiled everytime
cache:
  directories:
    - $TRAVIS_BUILD_DIR/build/GSL/src
    - $TRAVIS_BUILD_DIR/build/FFTW/src
    - $TRAVIS_BUILD_DIR/build/SWIG/src
    - $TRAVIS_BUILD_DIR/build/CLASS/src
    - $HOME/miniconda

# Definition of python build matrix for osx comes from:
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          python: 2.7
          sudo: required
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py36

#addons:
#    apt:
#        packages:
#            - texlive-latex-recommended
#            - texlive-latex-extra
#            - texlive-fonts-recommended
#            - texlive-fonts-extra
#            - dvipng

install:
    - ./.travis/install.sh
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then source $HOME/miniconda/bin/activate; fi
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then hash -r ; fi
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then source activate test-environment ; fi
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
    - cmake --version
    - python --version

script:
    - python setup.py build
    - python setup.py test
    - sudo make -Cbuild install
    - check_ccl

# Check why the note creation process crashes
#    - make -C doc/0000-ccl_note
#after_success:
#    if [[ -n "$GITHUB_API_KEY" ]; then
#        git checkout --orphan pdf
#        git rm -rf .
#        cp doc/0000-ccl_note/main.pdf 0000-ccl_note.pdf
#        git add -f 0000-ccl_note.pdf
#        git -c user.name='travis' -c user.email='travis' commit -m init
#        git push -q -f https://drphilmarshall:$GITHUB_API_KEY@github.com/DarkEnergyScienceCollaboration/CCL pdf
#    fi
