language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - fftw3
      - fftw3-dev
      - pkg-config
      - libgsl0-dev
      - swig
      - python-numpy
      - python3-numpy
      - cmake-data
      - cmake

install: true

script:
    - python setup.py build
    - python setup.py test
    - sudo make -Cbuild install
    - check_ccl
