language: c

# Compiler selection
compiler:
  - clang
  - gcc

# Installs system level dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fftw3 fftw3-dev pkg-config cmake libgsl0-dev swig python3-numpy

install: true

script:
    - mkdir build
    - cmake -H. -Bbuild
    - sudo make -Cbuild install
    - check_ccl
