language: python

# Caching GSL and CLASS
cache:
  directories:
    - $HOME/build/EiffL/CCL/build/GSL/src
    - $HOME/build/EiffL/CCL/build/FFTW/src
    - $HOME/build/EiffL/CCL/build/SWIG/src
    - $HOME/build/EiffL/CCL/build/CLASS/src

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.5"
  - "3.6"

install: true

script:
    - cmake --version
    - python setup.py build
    - python setup.py test
    - sudo make -Cbuild install
    - check_ccl
